### ISSUE TITLE
Rule34 links broken

### ISSUE THREAD

**Issue by NickGurMatic69** [TheSharks/WildBeastDocs#27]
Wildbot posts them with an extra http: which breaks the hyperlinking. https://i.imgur.com/FdQJRBd.png

**Comment by curtisf** [comment]
Thanks for the report. Regardless of the extra http, everything should still embed except for gifs and webms.

**Comment by Dougley** [comment]
This is not a documentation issue, bugs and/or problems related to WildBot go to https://github.com/TheSharks/WildBeast
