### ISSUE TITLE
Dockermentation

### ISSUE THREAD

**Issue by Dougley** [TheSharks/WildBeastDocs#7]
In line with https://github.com/TheSharks/WildBeast/pull/176, we need docs on how to setup Docker.
In short, steps consist of installing docker and running `docker-compose up` in the folder wildbeast was cloned to.

**Comment by linuswillner** [comment]
I'm already concepting it ;)

**Comment by linuswillner** [comment]
The progress with this is halted until we get the new website live.

**Comment by linuswillner** [comment]
Removed from init website release because I'm busy as hell. Writing when I can.

**Comment by linuswillner** [comment]
Took me forever but I've now written it up and resolved this in https://github.com/TheSharks/WildBeastDocs/commit/ee3bf6f5c367f74b2a2412b86393b01213efe591. It has also been put on the deck with the 4.1.0 documentation RC at https://github.com/TheSharks/WildBeastDocs/pull/13.

**Comment by linuswillner** [comment]
All clear.
